name: workshop_manager
description: A comprehensive workshop management system for Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Charts
  fl_chart: ^0.65.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  
  # HTTP & Networking
  http: ^1.1.2
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Toast & Dialogs
  fluttertoast: ^8.2.4
  
  # Loading & Progress
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: WorkshopIcons
      fonts:
        - asset: assets/fonts/WorkshopIcons.ttf