// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZ2d4tuh7OtPcHUmkPqNbEv_52Kblh90',
    appId: '1:643643416124:web:6b7e62f544402456a0ad39',
    messagingSenderId: '643643416124',
    projectId: 'workshop-management-sys',
    authDomain: 'workshop-management-sys.firebaseapp.com',
    storageBucket: 'workshop-management-sys.firebasestorage.app',
    measurementId: 'G-TW616QJGRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZ2d4tuh7OtPcHUmkPqNbEv_52Kblh90',
    appId: '1:643643416124:android:your_android_app_id',
    messagingSenderId: '643643416124',
    projectId: 'workshop-management-sys',
    storageBucket: 'workshop-management-sys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkZ2d4tuh7OtPcHUmkPqNbEv_52Kblh90',
    appId: '1:643643416124:ios:your_ios_app_id',
    messagingSenderId: '643643416124',
    projectId: 'workshop-management-sys',
    storageBucket: 'workshop-management-sys.firebasestorage.app',
    iosBundleId: 'com.example.workshopManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkZ2d4tuh7OtPcHUmkPqNbEv_52Kblh90',
    appId: '1:643643416124:macos:your_macos_app_id',
    messagingSenderId: '643643416124',
    projectId: 'workshop-management-sys',
    storageBucket: 'workshop-management-sys.firebasestorage.app',
    iosBundleId: 'com.example.workshopManager',
  );
}